### ISSUE TITLE
incorrect convert UVJ -> CTB files

### ISSUE THREAD

**Issue by winso2018** [ezrec/uv3dp#111]
for sample. CTB file (13 layers)
Original file - 1029kb

CTB -> UVJ - ok
uv3dp.exe file.ctb file.uvj (result file 322412b)

UVJ -> CTB - damaged file 
uv3dp.exe file.uvj file1.ctb (result file 41964 b). 
what to do?
[https://yadi.sk/d/GElSCuvc_Vf6FA](url)

**Comment by ezrec** [comment]
Thanks for the concise bug report - I've been able to reproduce the problem, and have found the root cause.

I should have a new release ready soon that fixes this issue.

**Comment by ezrec** [comment]
Will be fixed in release v1.2.3

Thanks for the bug report!
