### ISSUE TITLE
Feature Request - Remove unsupported islands/generate supports for islands.

### ISSUE THREAD

**Issue by Jorenm** [ezrec/uv3dp#125]
I would do this myself, but I don't know Go. 

I think it'd be cool to have a command to delete all unsupported pixels. I'm thinking one would test each pixel to ensure it has at least 1 (or configurable) pixel beneath/adjacent to it on the previous layer.

Another cool feature would be auto-supports. Take the unsupported islands discovered as above and add a support column going straight down until it contacts layers below it. This would be a brute force solution, but it would be useful in many situations.

**Comment by ezrec** [comment]
Cool feature proposal, but without visualization, it's hard to know if uv3dp doing the "right thing". There's a lot of edge cases where this would not be the ideal solution.

This may be something that [UVTools](https://github.com/sn4k3/UVtools) would be better suited for.
