### ISSUE TITLE
Converting a collection of layer images to a printable file format

### ISSUE THREAD

**Issue by Megidd** [ezrec/uv3dp#143]
Hi guys!

Thanks for the great project! 😄 

I want to use this repository to convert a collection of layer images into printable file formats, i.e. the supported formats.

I'm looking at the code, and my understanding is that the entry point for such an idea is to use `Printable` interface inside `printable.go`. But I don't know how to do it.

* I cannot figure out the best way to implement such an idea
* I'm just looking for some suggestions for code design and a proper approach
* Any hint which gets me started?

Thanks!

**Comment by Megidd** [comment]
#### Structures and interfaces

```
type Printable interface    // printable.go
type Format struct          // format.go
type Formatter interface    // format.go
type Print struct           // print.go
type Properties struct      // properties.go
type Print struct           // cbddlp\format.go
type Formatter struct       // cbddlp\format.go
...
```

These are all related somehow, but it's a bit hard to keep track 😕

**Comment by Megidd** [comment]
### Possible approach

Does this approach make sense?

* Let's create a new package named `imgcoll`
* It would be like `cbddlp`, `ctb`, `sl1`, ...
* New `imgcoll` package would be for a *collection of layer images* already available
* `imgcoll` package needs to implement `Decode` and `Encode` methods
* `imgcoll` `Decode` method would read image files and some properties by JSON files
   * It would return a `type Printable interface`
   * The return could be converted to any file format by the current uv3dp code design, right?
* `imgcoll` `Encode` method would write a compressed file containing all the image files and JSON files

If the above new package is implemented, then converting a collection of layer iamges to any file format would be straightforward. It would follow the current uv3dp code design. Is it right?

Any suggestion?

**Comment by ezrec** [comment]
How would this differ from the existing UVJ format (which is a zip of PNG layer images and JSON metadata?)

--
Jason S. McMullan

**Comment by Megidd** [comment]
@ezrec I wasn't aware of UVJ format functionality. I'm going to look into it. Thanks! :smiley:

**Comment by Megidd** [comment]
I tested the UVJ format. It works just fine 😃
