### ISSUE TITLE
Machine Kelant S400S - images not rotated

### ISSUE THREAD

**Issue by fourthsaxon** [ezrec/uv3dp#73]
When converting to machine Kelant-S400 the images are not rotated to landscape.
Result: images are portret after converting.
Expected result: images are landscape.

The resolution for this machine is:
;(X Resolution            = 2560 )
;(Y Resolution            = 1600 )
![afbeelding](https://user-images.githubusercontent.com/66954915/84700327-44d24a00-af53-11ea-9210-650609d72a69.png)

**Comment by ezrec** [comment]
Can you attach a small file 'ready for print' on the Kelant S400S? 

Preferably something that is small, and is not symmetric, for example a 2mm high text block.

I want to make sure I get the mirroring and rotations right.

**Comment by fourthsaxon** [comment]
[ReadForPrint_Kelant-S400S.zip](https://github.com/ezrec/uv3dp/files/4788504/ReadForPrint_Kelant-S400S.zip)

In the zip file you can find the sliced *.cbddlp file and the *.stl

Thank you for the fast action !

**Comment by ezrec** [comment]
Should be resolved in release 0.8.5
